<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location Name_searchLocationname</name>
   <tag></tag>
   <elementGuidId>354adade-83b0-4d7c-9f7d-2f7cf86399e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchLocation_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchLocation_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3afe7b7-6aa8-4139-81e6-9c70673e9da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1b0bc45a-ff29-43b4-b864-c586b2d21d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchLocation[name]</value>
      <webElementGuid>80e5895f-e71d-4a76-8b48-6a59b980318f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchLocation_name</value>
      <webElementGuid>ef6c9f98-e990-4c99-bb39-0654353fca01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchLocation_name&quot;)</value>
      <webElementGuid>2527a9a2-9625-43e8-adfc-4b76243f1a21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchLocation_name']</value>
      <webElementGuid>c5643849-19c6-49df-93f6-41080bccc774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSearchLocation']/fieldset/ol/li/input</value>
      <webElementGuid>7fbc2de6-e935-4976-91e5-46329bc83d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>676eb68f-aa79-459f-b8da-8e7fa8d69aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchLocation[name]' and @id = 'searchLocation_name']</value>
      <webElementGuid>7c40e3d1-a6be-4700-be36-7dc079dd62f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
