<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Country_btnSave</name>
   <tag></tag>
   <elementGuidId>d15adb04-9c8b-4e64-baf2-45287bb2ebb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78e92cee-cf67-4c48-9136-10b8c54b636a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d88d103-397c-4912-b8c6-b750b1af476f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addbutton hover</value>
      <webElementGuid>b7a0d103-2905-46a3-9216-c68afc20d66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSave</value>
      <webElementGuid>c80aca48-e03c-47c1-ba7a-aa23d7885746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSearch</value>
      <webElementGuid>9824c270-f687-4160-bc73-3e460d00e657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>77889f1f-cbad-46b5-b096-d29ba71cf909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>414a5c99-74b9-494c-8671-e48933a88b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSearch&quot;)</value>
      <webElementGuid>3c0115dc-b002-4bec-a8cd-2720ca1b17bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSearch']</value>
      <webElementGuid>5652f35d-e0a1-4476-a9f5-9aac6e892e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSearchLocation']/fieldset/p/input</value>
      <webElementGuid>ec24496a-eab5-442e-a086-09f36f80bb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>2eecbd71-8d82-40b8-ba03-1cf9bd3ecfbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnSave' and @id = 'btnSearch' and @title = 'Search']</value>
      <webElementGuid>c87ef717-8b29-47fd-84cd-c34eb1c0c271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
