<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>candidate dd-delete more</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c35ffc5f-16b3-4cda-817f-df177d599f17</testSuiteGuid>
   <testCaseLink>
      <guid>df29a491-223d-4051-9993-d498287bf70a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PROJECT WEB/000 NORMAL/CANDIDATE/Add Candidate/Positive/add candidate DD</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4fc8b6e9-e8c6-4c3c-87f3-2d9f7abea8c8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/WEB PROJECT/candidate data driven</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4fc8b6e9-e8c6-4c3c-87f3-2d9f7abea8c8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Fname</value>
         <variableId>a78435c8-902f-4a03-b468-e42b6f46bc11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4fc8b6e9-e8c6-4c3c-87f3-2d9f7abea8c8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Mname</value>
         <variableId>e3d4c788-571f-49c9-a3b3-b12bd4dc8d47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4fc8b6e9-e8c6-4c3c-87f3-2d9f7abea8c8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Lname</value>
         <variableId>8df055c4-e9c6-42ef-a2a4-630c344bc68f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4fc8b6e9-e8c6-4c3c-87f3-2d9f7abea8c8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>e9e23603-9521-4839-8638-c408e75f89aa</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
