<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Employee List</name>
   <tag></tag>
   <elementGuidId>d28ed300-aa1e-4dc3-83fb-94ef32f10c1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_pim_viewEmployeeList</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_pim_viewEmployeeList']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c5a01a4-c7b5-4a30-9c91-9613e8de3a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/pim/viewEmployeeList/reset/1</value>
      <webElementGuid>0d06e32f-1bdf-49ce-a6c5-4523f40d08d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_pim_viewEmployeeList</value>
      <webElementGuid>3685457c-0651-437e-b758-bfa57bac435c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee List</value>
      <webElementGuid>cee67874-1e4d-406c-b6c6-6807e9e65650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_pim_viewEmployeeList&quot;)</value>
      <webElementGuid>05796be0-d9bd-446d-8440-75312f4e7b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_pim_viewEmployeeList']</value>
      <webElementGuid>ea23c53c-11da-4985-8b43-5c45e3e6fc6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[2]/ul/li[2]/a</value>
      <webElementGuid>514a5407-a5a0-408d-a587-ba05b32127ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Employee List')]</value>
      <webElementGuid>78b18a39-ca01-431c-a5c0-737fe7e71384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Termination Reasons'])[1]/following::a[1]</value>
      <webElementGuid>e223e47c-b05c-4d29-af46-3dcf203900c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporting Methods'])[1]/following::a[2]</value>
      <webElementGuid>a46ef924-20b1-4cd1-b24c-638a6e747a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Employee'])[1]/preceding::a[1]</value>
      <webElementGuid>2cfcc070-d238-416b-b4b8-d3a6f3d83fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/preceding::a[2]</value>
      <webElementGuid>8b663713-d488-44c1-a4a4-410ca13fd014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Employee List']/parent::*</value>
      <webElementGuid>78f54257-12bb-4745-8317-f12f08c500f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/pim/viewEmployeeList/reset/1')]</value>
      <webElementGuid>b5a2c60d-26eb-4bf9-b90c-9a538e663bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/a</value>
      <webElementGuid>cf924fb4-ebc0-4612-954e-b852976f9cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/pim/viewEmployeeList/reset/1' and @id = 'menu_pim_viewEmployeeList' and (text() = 'Employee List' or . = 'Employee List')]</value>
      <webElementGuid>f991e145-b4e1-45ae-99cd-e7e827f0cbc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
