<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sub Unit_btnDelete</name>
   <tag></tag>
   <elementGuidId>c799eb3a-2147-4265-a348-e4e464282a06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDelete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnDelete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d914ce20-6b61-4186-95f9-83ced2183f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3b1f0316-8623-420d-8491-00b58b54c9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>delete hover</value>
      <webElementGuid>326c3090-a429-4be6-ad78-73a9a9b7b02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDelete</value>
      <webElementGuid>643b11d5-7ec1-4818-b65a-516638a1d6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnDelete</value>
      <webElementGuid>368389a6-9b71-4808-b945-075b5a4ee126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>0c9b4324-06d8-4a60-8842-3433aae078e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>5dd47b82-275d-4ad6-9c41-638890f6b2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#deleteConfModal</value>
      <webElementGuid>3f415281-2e4f-426c-b751-ff599d9b5d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDelete&quot;)</value>
      <webElementGuid>66c67a29-c530-40dc-8c90-98d5c1773426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnDelete']</value>
      <webElementGuid>127cb54e-a895-4e4d-addd-e163f5f076de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmList_ohrmListComponent']/div/input[2]</value>
      <webElementGuid>756115b4-4ccb-4647-ba94-6922d50f9d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input[2]</value>
      <webElementGuid>1a5bb671-799f-4f64-91de-87247db074bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'btnDelete' and @name = 'btnDelete']</value>
      <webElementGuid>a12f9ae3-70df-4b7c-8f5c-54e22c55196d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
