<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Name_empsearchemployee_nameempName</name>
   <tag></tag>
   <elementGuidId>9170433d-5d33-45cb-8ad5-76e2defeea8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empsearch_employee_name_empName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empsearch_employee_name_empName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95818605-3930-4c26-9ec1-bf65d4b75e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c8b906a-5432-4ad4-90b6-3f5b8bfe28e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empsearch[employee_name][empName]</value>
      <webElementGuid>4b1e495c-8e48-4b9c-8fa7-6a3382848a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empsearch_employee_name_empName</value>
      <webElementGuid>bebda9d3-a3c9-47cc-924a-5621a99b66da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>a6713b12-abc1-4904-9fea-e67bc3a1941c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>42ebe103-b036-4604-9ae0-63d1fc010d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empsearch_employee_name_empName&quot;)</value>
      <webElementGuid>f5977343-3d85-4ed7-848f-b051bd6b33d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empsearch_employee_name_empName']</value>
      <webElementGuid>b695b9c4-3608-42cb-95cd-4b0d0624a55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li/input</value>
      <webElementGuid>492afa6d-df01-4b75-8d08-f88e99044952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>b8951853-5b85-4c10-b4fa-43e681df53a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'empsearch[employee_name][empName]' and @id = 'empsearch_employee_name_empName']</value>
      <webElementGuid>3e46d744-1abf-4eee-8c4d-546c05ed9542</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
