<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Name_empsearchemployee_nameempName</name>
   <tag></tag>
   <elementGuidId>9170433d-5d33-45cb-8ad5-76e2defeea8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empsearch_employee_name_empName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empsearch_employee_name_empName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e010bb5-c2a2-4d4f-97aa-55549e81b6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12b83f19-7d22-4474-a803-d6002b0a9b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empsearch[employee_name][empName]</value>
      <webElementGuid>d18a4ac7-12d9-4443-b042-2dbec049716d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empsearch_employee_name_empName</value>
      <webElementGuid>f3293346-5b54-4bd4-be80-a16d41d72a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>5e75ae58-5b16-4acf-8f1f-4b3773126beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5de7a1bf-776f-45a4-9552-309390466a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empsearch_employee_name_empName&quot;)</value>
      <webElementGuid>2543e9aa-953d-4da5-9910-9338526e452b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empsearch_employee_name_empName']</value>
      <webElementGuid>1527268f-c01c-4f83-840e-9844ba617aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/fieldset/ol/li/input</value>
      <webElementGuid>445eb4fb-3581-4c00-a213-40517ef11124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>ba38628c-d065-4d91-a54f-87e73c87bd1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'empsearch[employee_name][empName]' and @id = 'empsearch_employee_name_empName']</value>
      <webElementGuid>246a2695-c41a-4f25-950d-f117fff3f097</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
