<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Username</name>
   <tag></tag>
   <elementGuidId>9c7d50af-2e9e-4e9d-97b0-32ca528469bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.form-hint</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divUsername']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>46a65d73-7b41-4fc8-b8a4-35bcdf8382fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-hint</value>
      <webElementGuid>ca13394f-f006-4434-87b5-345d0559590c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>f766671f-33aa-4f31-8538-e28cc6a88db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divUsername&quot;)/span[@class=&quot;form-hint&quot;]</value>
      <webElementGuid>dadbee62-aba5-4ed5-b249-9f4e54c8a1cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divUsername']/span</value>
      <webElementGuid>84448dce-1cd7-46bf-96f7-8a8d838c135d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN Panel'])[1]/following::span[1]</value>
      <webElementGuid>a51d12fb-1a9a-4cfe-8fdb-e4989acfde17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='( Username : Admin | Password : admin123 )'])[1]/following::span[1]</value>
      <webElementGuid>7df584f2-c019-47f8-9e5d-35bf99596900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::span[1]</value>
      <webElementGuid>ff6ab2f0-a070-4536-b3ca-d454273bd334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot your password?'])[1]/preceding::span[2]</value>
      <webElementGuid>c136ba45-8b66-4471-8cb7-92ce59d63c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Username']/parent::*</value>
      <webElementGuid>ad3d5e36-5935-48c8-b4df-5f5b9de52908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/span</value>
      <webElementGuid>a8a8fb80-6083-4b2e-bd65-8e2f4e05b458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Username' or . = 'Username')]</value>
      <webElementGuid>d9eb70b2-2b12-47f9-ade4-121667898c6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
