<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Middle Name_addCandidatemiddleName</name>
   <tag></tag>
   <elementGuidId>b740b9a7-847c-4299-b889-5064b3139dd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addCandidate_middleName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addCandidate_middleName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95466245-c923-435b-a9b3-8f21160ca8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4d66c48-56bf-4b33-9e67-fa280a31a9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addCandidate[middleName]</value>
      <webElementGuid>e6ca32a6-382c-4891-882d-de497e7a15ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>2dce787a-f727-4f42-9897-b2f6dbea3213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>d2a9e38c-77e8-4162-94d7-518a5d099912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addCandidate_middleName</value>
      <webElementGuid>a521a3f4-d842-4f1b-9d03-7763f821eda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addCandidate_middleName&quot;)</value>
      <webElementGuid>bcb02074-2a44-4496-ac3f-062ffe6f6a47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addCandidate_middleName']</value>
      <webElementGuid>ed9f1fb9-92c7-45df-997a-35bcc0e9410d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddCandidate']/fieldset/ol/li/ol/li[2]/input</value>
      <webElementGuid>ae7530d7-b510-4973-8649-2fa904f57595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ol/li[2]/input</value>
      <webElementGuid>7efac8de-daab-47cb-80db-dc283589fcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addCandidate[middleName]' and @id = 'addCandidate_middleName']</value>
      <webElementGuid>4fc4ed41-5ef8-42a9-af2f-44abf05262a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
