<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Candidate Name_candidateSearchcandidateName</name>
   <tag></tag>
   <elementGuidId>df80c2ad-f8f5-4966-8130-199eb4936843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#candidateSearch_candidateName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='candidateSearch_candidateName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>179a2d4a-7d34-48b0-b99f-a8e7fb7b92cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2803e769-2537-46a3-9f2d-525057d6197e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>candidateSearch[candidateName]</value>
      <webElementGuid>80a24fd5-e194-4cc8-8c63-ba28e4b2b3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>candidateSearch_candidateName</value>
      <webElementGuid>47514558-45e6-446f-ba92-a8c08b00c3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dd54836b-5dd0-4a25-a5b0-29163f22ebb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>4d6ab8c7-6b30-4cf3-ad89-e474aeaf9f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateSearch_candidateName&quot;)</value>
      <webElementGuid>d46cad18-3576-4e9b-8b83-dc39700e4621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='candidateSearch_candidateName']</value>
      <webElementGuid>63cc4a7d-eb48-4f24-9eb0-c0af6786306b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSrchCandidates']/fieldset/ol/li[5]/input</value>
      <webElementGuid>0d9cd7d7-4468-482f-b047-84036fbe230f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/input</value>
      <webElementGuid>cf621c3d-9c3e-4e43-aea6-d1abdb8d4946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'candidateSearch[candidateName]' and @id = 'candidateSearch_candidateName']</value>
      <webElementGuid>e354bdcd-a521-4221-925d-ffec0d33c76c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
