<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__addCandidateemail</name>
   <tag></tag>
   <elementGuidId>392fa3e4-63e9-49cf-b1a6-e0804bf789ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addCandidate_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addCandidate_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6f5a24e-2953-4371-80f4-48322a6593ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44eeb6ec-28d0-410f-8930-6eeb293813c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addCandidate[email]</value>
      <webElementGuid>60ed3cd7-69f3-4582-b29c-bb94f61dacdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>b5522fcf-8b49-4a2f-8a6a-0d323b643cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addCandidate_email</value>
      <webElementGuid>e2a4b49f-0a89-47cc-b3d2-e2deea12288f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addCandidate_email&quot;)</value>
      <webElementGuid>f8f7b5a7-ae4e-4e2b-ab4b-f858df1ad302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addCandidate_email']</value>
      <webElementGuid>c9e5bebe-0d90-4c19-81b7-1ee34ffeac44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddCandidate']/fieldset/ol/li[2]/input</value>
      <webElementGuid>d6c22646-4b72-4c46-b25e-d8fc24b3bd06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>6a0c3bb2-27cb-416d-8dbf-f244b1b57399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addCandidate[email]' and @id = 'addCandidate_email']</value>
      <webElementGuid>01a9d268-9c33-4c3c-ae68-ba6b86ba5b13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
