<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Method of Application_btnSrch</name>
   <tag></tag>
   <elementGuidId>6f86eb85-3494-4629-9d2e-ac1a9ca28e40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSrch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSrch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40d4de13-8831-4f0b-ae9e-21ccedebd916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e63f54d-09ac-4ffa-b723-c3f51a02e376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSrch</value>
      <webElementGuid>9b45e183-d3cf-41e1-9b59-8403a7a7aaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>b1c35bfa-b808-4fcd-b195-df09f0aea2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSrch</value>
      <webElementGuid>4e3e1e6d-375b-4b2b-a80c-ca244e9dd017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover</value>
      <webElementGuid>2e015e1a-2ada-4123-8758-0c0b3d70bc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSrch&quot;)</value>
      <webElementGuid>6e271ffa-6993-49e4-a6c3-b64d5dc46bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSrch']</value>
      <webElementGuid>c17a15a9-b1ac-4433-9721-45ecc7c2457b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSrchCandidates']/fieldset/p/input</value>
      <webElementGuid>63fe9e2e-0597-4614-8bec-31b895c86089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>0f58aac7-f50d-4ede-9aa9-7c3c9ef85d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnSrch' and @name = 'btnSrch']</value>
      <webElementGuid>94c783b2-ebf6-4ace-8083-603ef2e22c87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
