<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__addCandidatefirstName</name>
   <tag></tag>
   <elementGuidId>9b6159ec-8391-4aef-80f2-9e33fe165111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addCandidate_firstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addCandidate_firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ca2dc81-21e1-4dd7-b1a3-efef29f294ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5c9d3769-0bf6-436e-a5d9-70ef107d1b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addCandidate[firstName]</value>
      <webElementGuid>7eded1a3-3acb-4326-b94d-a369fff424b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInputText</value>
      <webElementGuid>64a20452-272c-4368-a997-b751698d74e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>83aee058-1ec8-4d61-b185-2cbb92905522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addCandidate_firstName</value>
      <webElementGuid>031e5c94-1b1a-4b34-8432-64425d5bc669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addCandidate_firstName&quot;)</value>
      <webElementGuid>a23b81fa-389d-42ea-ab20-5b52722df368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addCandidate_firstName']</value>
      <webElementGuid>746160bc-d76c-4cf0-87ab-14877665fcce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmAddCandidate']/fieldset/ol/li/ol/li/input</value>
      <webElementGuid>1f58707e-8a31-4566-a63e-0b3a06bdae1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>6035ff41-fcf1-4b04-89fd-fcbe2a5887bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addCandidate[firstName]' and @id = 'addCandidate_firstName']</value>
      <webElementGuid>60f40dc8-7eae-4d56-8e12-1b89c6ff8cae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
