<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Date of Application2</name>
   <tag></tag>
   <elementGuidId>3abbd176-dde5-4148-89a9-1fc5e7318f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ASC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='resultTable']/thead/tr/th[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6b937227-e1d5-4aaa-a2f4-b6d28072aaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://opensource-demo.orangehrmlive.com/index.php/recruitment/viewCandidates?sortField=jc.date_of_application&amp;sortOrder=DESC</value>
      <webElementGuid>fe9115db-68c9-4888-b88d-f96569c33c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ASC</value>
      <webElementGuid>d0b72f27-934a-4a8c-86ac-1a1425371e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date of Application</value>
      <webElementGuid>4f4980be-4431-403d-8cfe-2f77213e9b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultTable&quot;)/thead[1]/tr[1]/th[@class=&quot;header headerSortUp&quot;]/a[@class=&quot;ASC&quot;]</value>
      <webElementGuid>89f2d88f-88b4-41f8-b64f-b9dd7bad6066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/thead/tr/th[5]/a</value>
      <webElementGuid>1b8b1b87-3b73-4504-9d2c-1917faa8828f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Date of Application')]</value>
      <webElementGuid>36d7d8a8-c9df-45e9-9732-bf5199d13778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hiring Manager'])[2]/following::a[1]</value>
      <webElementGuid>6df13027-83a4-4b3b-a619-13a3e79ca9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Candidate'])[1]/following::a[2]</value>
      <webElementGuid>9ce85602-bfcd-4f9b-86e0-3e84a1fe8d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/preceding::a[1]</value>
      <webElementGuid>7ba2e720-a3cd-4c34-b853-658e557d663f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resume'])[1]/preceding::a[2]</value>
      <webElementGuid>fc186035-9b05-43d5-846b-e5a4af032d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://opensource-demo.orangehrmlive.com/index.php/recruitment/viewCandidates?sortField=jc.date_of_application&amp;sortOrder=DESC')]</value>
      <webElementGuid>96c54f50-0f3e-460c-97a3-2bd49610c047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/a</value>
      <webElementGuid>0a2497c9-9d26-42b5-adab-6fdc9c7b53b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://opensource-demo.orangehrmlive.com/index.php/recruitment/viewCandidates?sortField=jc.date_of_application&amp;sortOrder=DESC' and (text() = 'Date of Application' or . = 'Date of Application')]</value>
      <webElementGuid>f5cbba59-b0aa-4ba1-b3d9-e528d7dbb30f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
