<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OrangeHRM - Confirmation Required_dia_9fc7db</name>
   <tag></tag>
   <elementGuidId>f371fe98-f910-4ae9-93da-5e599ebe401d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dialogDeleteBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dialogDeleteBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02e2f66d-1f80-4f0e-8b41-437d9870c3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>574c40db-2d2b-4326-936c-1761470299dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn hover</value>
      <webElementGuid>7514db70-b23c-44d2-8c99-52d8d598c7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>00a2333c-fbc3-4d9a-9ec2-0607700ecea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialogDeleteBtn</value>
      <webElementGuid>e2aae088-fd87-4f0d-ba26-86c8f33a84ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>a1612574-b1ee-4da1-97d1-883ee5797759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogDeleteBtn&quot;)</value>
      <webElementGuid>81250507-cdcf-429c-a737-a078f584bb14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dialogDeleteBtn']</value>
      <webElementGuid>5dcfa514-6b9d-41cc-b70a-094734f577a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deleteConfirmation']/div[3]/input</value>
      <webElementGuid>a0809951-d497-4a8e-bc64-fd00534daac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>aa5677a1-4ec8-433d-ba72-807fb633f90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'dialogDeleteBtn']</value>
      <webElementGuid>c2bc1689-7f67-4c85-bf0b-cdc764ed6dcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
