<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Download_chkSelectRow</name>
   <tag></tag>
   <elementGuidId>e2dd3444-46f8-4132-8b0f-82c7365ffe4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ohrmList_chkSelectRecord_25_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ohrmList_chkSelectRecord_25_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bfa64e6-0490-494f-96bd-686df3aa2276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ad5b3fed-bca1-4758-90eb-b55ffb25ed84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ohrmList_chkSelectRecord_25_2</value>
      <webElementGuid>ead4e350-0638-4211-b1cd-bb2e3b5d4067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkSelectRow[]</value>
      <webElementGuid>76155262-ba96-4c0c-99a6-4f2e31e03faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>25_2</value>
      <webElementGuid>d24338e1-c770-44b9-b0a3-bd3a37ab11a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ohrmList_chkSelectRecord_25_2&quot;)</value>
      <webElementGuid>5aa82d46-b117-4741-9d78-3bc7c8a7603e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ohrmList_chkSelectRecord_25_2']</value>
      <webElementGuid>7bf55b23-14bb-4004-9896-ce65469f57a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/tbody/tr[2]/td/input</value>
      <webElementGuid>51cfe979-1649-4a8d-aee8-06d1c8326cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>0afa3d9d-3a27-486d-b6f8-c8c231006833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ohrmList_chkSelectRecord_25_2' and @name = 'chkSelectRow[]']</value>
      <webElementGuid>60989de4-6ee3-4608-bde0-147df755b25d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
