<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Candidate Name_candidateSearchcandidateName</name>
   <tag></tag>
   <elementGuidId>1d1a7b24-6b0b-49a5-bcd1-7453c5bcfa4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='candidateSearch_candidateName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#candidateSearch_candidateName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0518bac4-18ae-42ed-9b78-1e375a512694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d96a595d-0f32-4183-bd6e-2a172f34b31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>candidateSearch[candidateName]</value>
      <webElementGuid>32642432-d0dc-4ae0-b26e-bceffe7533e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>candidateSearch_candidateName</value>
      <webElementGuid>2b7bdeac-82b5-4872-886d-07499205ba59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>995a28b9-5163-4028-9fef-9a0340082d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac_input</value>
      <webElementGuid>915d6c1d-f445-4d2d-8c55-88ec585f69c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;candidateSearch_candidateName&quot;)</value>
      <webElementGuid>d8e3c5c1-2b10-4ea6-9829-42e375ade74c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='candidateSearch_candidateName']</value>
      <webElementGuid>b5074390-47b7-44c4-b113-fa54def0016d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSrchCandidates']/fieldset/ol/li[5]/input</value>
      <webElementGuid>254757d6-8dc9-41c8-9c65-4c62b640612f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/input</value>
      <webElementGuid>d758a58b-c25b-4249-acb9-15d6be5dc9ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'candidateSearch[candidateName]' and @id = 'candidateSearch_candidateName']</value>
      <webElementGuid>fd2fa668-da44-4cc3-ba01-979f62889f48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
